class CycleError(Exception):
    """Raises when trying to move task to own subtask"""
    pass
